# K8s Manifests for Backstage POC
# Based on official Backstage dice-roller example

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  labels:
    'backstage.io/kubernetes-id': payment-api
spec:
  selector:
    matchLabels:
      app: payment-api
  replicas: 3
  template:
    metadata:
      labels:
        app: payment-api
        'backstage.io/kubernetes-id': payment-api
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          resources:
            requests:
              memory: '64Mi'
              cpu: '50m'
            limits:
              memory: '128Mi'
              cpu: '50m'
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api-canary
  labels:
    'backstage.io/kubernetes-id': payment-api
spec:
  selector:
    matchLabels:
      app: payment-api-canary
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-api-canary
        'backstage.io/kubernetes-id': payment-api
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: '64Mi'
              cpu: '50m'
            limits:
              memory: '128Mi'
              cpu: '100m'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api-bad-image
  labels:
    'backstage.io/kubernetes-id': payment-api
spec:
  selector:
    matchLabels:
      app: payment-api-bad-image
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-api-bad-image
        'backstage.io/kubernetes-id': payment-api
    spec:
      containers:
        - name: nginx
          image: nginx:9999999
          resources:
            requests:
              memory: '64Mi'
              cpu: '50m'
            limits:
              memory: '128Mi'
              cpu: '100m'
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-api
  labels:
    'backstage.io/kubernetes-id': payment-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: payment-api-cleanup
  labels:
    'backstage.io/kubernetes-id': payment-api
spec:
  schedule: '*/5 * * * *'
  jobTemplate:
    metadata:
      labels:
        'backstage.io/kubernetes-id': payment-api
    spec:
      template:
        metadata:
          labels:
            'backstage.io/kubernetes-id': payment-api
        spec:
          containers:
            - name: busybox
              image: busybox
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - date; echo Running payment cleanup job
          restartPolicy: OnFailure

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-api
  labels:
    'backstage.io/kubernetes-id': payment-api
data:
  API_VERSION: v1
  ENVIRONMENT: demo

---
apiVersion: v1
kind: Service
metadata:
  name: payment-api
  labels:
    'backstage.io/kubernetes-id': payment-api
spec:
  selector:
    app: payment-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
